const fs=require('node:fs');
const catalog=require('../products/catalog.json');
const origin='https://www.concursotrilhaaprova.online';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const products=Object.values(catalog).filter(p=>p.active);
const footer=fs.readFileSync('lib/site-footer.html','utf8');
const org={'@type':'Organization','@id':origin+'/#organization',name:'Trilha Aprova',url:origin+'/',email:'suporte@concursotrilhaaprova.online',areaServed:{'@type':'Country',name:'Brasil'}};
const json=v=>JSON.stringify(v).replace(/</g,'\\u003c');
function meta(title,description,path,nodes=[]){return `<!-- seo:start --><link rel="canonical" href="${origin}${path}"><meta name="robots" content="index,follow,max-image-preview:large"><meta property="og:type" content="website"><meta property="og:locale" content="pt_BR"><meta property="og:site_name" content="Trilha Aprova"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${origin}${path}"><meta property="og:image" content="${esc(products[0].storefront.cover3d)}"><meta name="twitter:card" content="summary_large_image"><script type="application/ld+json">${json({'@context':'https://schema.org','@graph':[org,...nodes]})}</script><!-- seo:end -->`;}
function page(path,title,description,body,nodes=[]){fs.mkdirSync('public'+path.substring(0,path.lastIndexOf('/')),{recursive:true});fs.writeFileSync('public'+path+'.html',`<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}">${meta(title,description,path,nodes)}<link rel="stylesheet" href="/legal.css"><link rel="stylesheet" href="/site-footer.css"><link rel="stylesheet" href="/newsletter.css"><link rel="stylesheet" href="/seo.css"></head><body><header class="guide-header"><a href="/">Trilha Aprova</a><nav><a href="/concursos-baixada-santista">Concursos na Baixada</a><a href="/como-estudar-com-apostila-e-audiobook">Como estudar</a><a href="/contato">Atendimento</a></nav></header><main class="guide"><a href="/">Início</a>${body}</main>${footer}<script src="/newsletter.js" defer></script><script src="/cookie-consent.js" defer></script><script src="/analytics-crm.js" defer></script></body></html>`);}
const links=products.map(p=>`<li><a href="/apostilas/${p.slug}">${esc(p.shortName)}</a> — PDF, resumo em áudio e ${p.assets.chapters.length} capítulos. ${esc(p.audience)}.</li>`).join('');
for(const p of products){const path='/apostilas/'+p.slug;const price=(p.priceCents/100).toFixed(2);const title=p.shortName+' com audiobook | Trilha Aprova';page(path,title,p.description,`<p class="eyebrow">${esc(p.edition)} · ${esc(p.category)}</p><h1>${esc(p.shortName)} com audiobook</h1><div class="product-intro"><img src="${esc(p.storefront.cover3d)}" alt="Capa de ${esc(p.shortName)}" width="360" height="450"><div><p>${esc(p.description)}</p><p><strong>Para quem:</strong> ${esc(p.audience)}.</p><p>Autoria: ${esc(p.author)}.</p><p class="guide-price">R$ ${price.replace('.',',')}</p><p>Pagamento único. Material digital em português, disponível online em todo o Brasil.</p><a class="guide-button" href="/comprar?produto=${p.slug}">Comprar PDF + audiobook</a></div></div><h2>O que está incluído</h2><ul>${p.proofPoints.map(t=>`<li>${esc(t)}</li>`).join('')}</ul><h2>Resumo em áudio e capítulos</h2><p>${esc(p.assets.summary.title)}. O resumo é uma revisão complementar; os capítulos organizam o estudo por assunto.</p><ol>${p.assets.chapters.map(c=>`<li><strong>${esc(c.title)}</strong><p>${esc(c.subtitle)}</p></li>`).join('')}</ol><h2>Este material serve para o meu concurso?</h2><p>${p.slug.startsWith('autores')?'Esta apostila revisa autores para Professor Adjunto I e Professor Adjunto II — Educação Especial, com foco na banca IBAM e na edição Santos 2026. Não substitui o estudo de todas as disciplinas do edital.':'Esta apostila trabalha redação para candidatos de ensino fundamental completo. O gênero textual e os critérios cobrados variam conforme o edital; não é uma apostila específica de todas as disciplinas de um cargo.'} Confira o conteúdo programático e as retificações no site oficial antes de comprar.</p><h2>Como recebo os arquivos?</h2><p>Após a confirmação do pagamento, sua área individual libera o PDF e os áudios desta apostila para leitura, reprodução e download. <a href="/entrega-e-acesso">Veja como funciona o acesso</a>.</p><p>Material independente, sem vínculo com órgãos públicos ou bancas. Não há garantia de aprovação.</p><h2>Continue sua preparação</h2><ul>${links}</ul><p><a href="/concursos-baixada-santista">Como organizar os estudos para concursos na Baixada Santista</a></p>`,[{'@type':'Product','@id':origin+path+'#product',name:p.shortName,description:p.description,image:p.storefront.cover3d,sku:p.slug,brand:{'@type':'Brand',name:'Trilha Aprova'},offers:{'@type':'Offer',url:origin+path,price,priceCurrency:'BRL',availability:'https://schema.org/InStock',seller:{'@id':origin+'/#organization'}}},{'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Início',item:origin+'/'},{'@type':'ListItem',position:2,name:p.shortName,item:origin+path}]}]);}
const guides=require('../content/search-guides.json');
for(const g of guides)page('/'+g.slug,g.title+' | Trilha Aprova',g.description,`<p class="eyebrow">GUIA DE ESTUDO</p><h1>${esc(g.title)}</h1><p>${esc(g.description)}</p>${g.body}<h2>Apostilas disponíveis com audiobook</h2><ul>${links}</ul>`);
let home=fs.readFileSync('public/index.html','utf8').replace(/<!-- seo:start -->[\s\S]*?<!-- seo:end -->/g,'').replace(/<meta name="google-site-verification"[^>]*>/g,'').replace(/<!-- discovery:start -->[\s\S]*?<!-- discovery:end -->/g,'');
const title='Apostilas para concursos com audiobook | Trilha Aprova';const description='Apostilas em PDF com audiobook e resumo em áudio. Autores IBAM para Santos e redação de nível fundamental. Estude na Baixada Santista e em todo o Brasil.';
home=home.replace(/<title>[\s\S]*?<\/title>/,`<title>${title}</title>`).replace(/<meta name="description" content="[^"]*">/,`<meta name="description" content="${description}">`).replace('</head>',meta(title,description,'/',[{'@type':'WebSite','@id':origin+'/#website',name:'Trilha Aprova',url:origin+'/',inLanguage:'pt-BR',publisher:{'@id':origin+'/#organization'}}])+'</head>');
home=home.replace('</main>',`<!-- discovery:start --><section class="section shell"><div class="section-heading"><span class="eyebrow">ENCONTRE SUA PRÓXIMA LEITURA</span><h2>Apostilas para concursos com PDF e audiobook</h2><p>Conheça o conteúdo de cada material antes de comprar. Os arquivos são digitais, com acesso em todo o Brasil.</p></div><ul>${links}</ul><h3>Preparação no litoral de São Paulo</h3><p>Estuda para concursos em Santos ou em outra cidade da Baixada Santista? Confira como comparar o edital com o material e organizar leitura, exercícios e revisão em áudio.</p><ul>${guides.map(g=>`<li><a href="/${g.slug}">${esc(g.title)}</a></li>`).join('')}</ul></section><!-- discovery:end --></main>`);const verification=process.env.GOOGLE_SITE_VERIFICATION; if(verification){if(!/^[A-Za-z0-9_-]{10,200}$/.test(verification))throw new Error('Invalid Search Console verification token');home=home.replace('</head>',`<meta name="google-site-verification" content="${verification}"></head>`);} fs.writeFileSync('public/index.html',home);
const paths=['/',...products.map(p=>'/apostilas/'+p.slug),...guides.map(g=>'/'+g.slug),'/contato','/termos','/privacidade','/cookies','/cancelamentos','/entrega-e-acesso'];
fs.writeFileSync('public/sitemap.xml','<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+paths.map(p=>`<url><loc>${origin}${p}</loc></url>`).join('')+'</urlset>\n');
fs.writeFileSync('public/robots.txt',`User-agent: *\nAllow: /\nDisallow: /api/\nDisallow: /acesso\n\nSitemap: ${origin}/sitemap.xml\n`);
for(const name of ['dashboard','comprar','obrigado','recuperar']){const f='public/'+name+'.html';let h=fs.readFileSync(f,'utf8');h=h.replace(/<meta name="robots"[^>]*>/g,'').replace('</head>','<meta name="robots" content="noindex,nofollow"></head>');fs.writeFileSync(f,h);}
console.log(`SEO: ${paths.length} public URLs, ${products.length} catalog-backed product pages; private files excluded.`);

for(const name of ['contato','termos','privacidade','cookies','cancelamentos','entrega-e-acesso']){const f='public/'+name+'.html';let h=fs.readFileSync(f,'utf8').replace(/<!-- seo:start -->[\s\S]*?<!-- seo:end -->/g,'');const title=h.match(/<title>(.*?)<\/title>/)?.[1]||'Trilha Aprova';h=h.replace('</head>',meta(title,'Informações da Trilha Aprova: '+title,'/'+name)+'</head>');fs.writeFileSync(f,h);}
